title: Society of Software Engineers
markdown: redcarpet
future:   true
pygments: true

paginate: 5
paginate_path: blog/index.html
exclude: ["Gemfile", "Gemfile.lock", "package.json", ".sass-cache", ".gitignore", "node_modules", "README.md", ".gitmodules", ]

redcarpet:
  extensions:
    - tables