title: Society of Software Engineers
markdown: redcarpet
future:   true
higlighter: pygments

paginate: 5
paginate_path: blog/:num
exclude: ["Gemfile", "Gemfile.lock", "package.json", ".sass-cache", ".gitignore", "node_modules", "README.md", ".gitmodules", "CONTRIBUTING.md", "tmp", 'config.ru', 'Rakefile', 'unicorn.rb']

redcarpet:
  extensions:
    - tables

relative_permalinks: false

sass:
  sass_dir: assets/css
  style: compressed
coffee:
  coffee_dir: assets/js
  style: compressed