title: Society of Software Engineers
markdown: redcarpet
future:   true
higlighter: pygments

paginate: 5
paginate_path: blog/:num
exclude: ["Gemfile", "Gemfile.lock", "package.json", ".sass-cache", ".gitignore", "node_modules", "README.md", ".gitmodules", "CONTRIBUTING.md", "tmp", 'config.ru', 'Rakefile', 'unicorn.rb']

redcarpet:
  extensions:
    - tables

sass:
  sass_dir: assets/css
  style: compressed
coffee:
  coffee_dir: assets/js
  style: compressed

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: pages/committees/talks
    values:
      sidebars:
        - _secondary_nav.html
      nav_links:
        - name: Talk Guidelines
          path: /committees/talks/guidelines/
        - name: Recorded Tech Talks
          path: /committees/talks/tech/
        - name: Recorded Micro Talks
          path: /committees/talks/micro/
        - name: Recorded Rand Talks
          path: /committees/talks/rand/
        - name: Recorded Alum Talks
          path: /committees/talks/alum/
collections:
  meeting_minutes:
    output: true
